language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "4.0"
  - "4.1"
  - "4.2"
  - "5.0"
  - "5.1"
  - "5.2"
  - "5.3"
services:
  - mongodb
before_script:
  - mysql -e 'create database raddish_demo; use raddish_demo; create table if not exists menu_items (menu_item_id bigint(20) not null auto_increment,title varchar(255),component varchar(255),primary key(`menu_item_id`)); create table if not exists bank_accounts (bank_account_id bigint(20) not null auto_increment,amount varchar(255),component varchar(255),primary key(`bank_account_id`));'
script: "npm run-script test-travis"
after_script: "npm install codeclimate-test-reporter && cat ./coverage/lcov.info | codeclimate-test-reporter"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: 47c1e110072a9d9a9adc4519d6a62cb1e116d52f8b49ac66d15bc28e97cd2b41
env:
  - CXX=g++-4.8
